### ISSUE TITLE
Ejercicio no linkado

### ISSUE THREAD

**Issue by JimenaEB** [breatheco-de/exercise-collaborative-html-website#21]
Este ejercicio no les aparece a los alumnos en su syllabus, por ello aunque se les pase el enunciado no pueden entregarlo.

**Comment by alesanchezr** [comment]
En realidad este no es un entregable sino una dinamica grupal, por eso no se coloca como tarea, la idea es terminarlo en clase y que el profesor demuestre como todo se conecta haciendo pull/merge.
