### ISSUE TITLE
Sugerencia enunciado

### ISSUE THREAD

**Issue by JimenaEB** [breatheco-de/exercise-collaborative-html-website#22]
Creo que más que dejarles que se copien la web que quieran es mejor que copien la del ejemplo del gif para que no pierdan tiempo ni el hilo.
Si optamos porque copien la del gif habría que añadir la imagen final en el enunciado porque con el gif no pueden ver bien que tienen que hacer.

Ya me dices @alesanchezr

**Comment by alesanchezr** [comment]
Esta bien, estoy de acuerdo que tal vez no es tiempo para los alumnos de ser creativos todavía 😆

**Comment by alesanchezr** [comment]
He actualizado el enunciado y agregado links para el diseño a completar y como dividir el website entre los alumnos.
