### ISSUE TITLE
Spanish Version Not Available

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/exercise-collaborative-html-website#45]
![image](https://user-images.githubusercontent.com/48845580/118007182-e86ddb00-b319-11eb-950a-bd1115886972.png)

It's not possible to choose the Spanish version

**Comment by ElviraQDP** [comment]
It will be translated by tomorrow

**Comment by jatv93** [comment]
I think it is translated already, I can see the readme in Spanish, the problem is that is not shown on the platform, the Spanish flag is not available @ElviraQDP

**Comment by ElviraQDP** [comment]
could you please leave an url  next time? it's easier! thank you!
